In [43]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))



[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
import pandas as pd
arr2=np.array(42)
print(arr2)

42


In [3]:
import numpy as np
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)


[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr4=np.array([[[3,4,5],[6,7,8]],[[1,2,3],[4,8,9]]])
print(arr4)

[[[3 4 5]
  [6 7 8]]

 [[1 2 3]
  [4 8 9]]]


In [11]:
print(arr1.ndim)

1


In [13]:
 print(arr2.ndim)

0


In [15]:
print(arr3.ndim)

2


In [17]:
print(arr4.ndim)

3


In [19]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:',arr[1,4])

5th element on 2nd row: 10


In [23]:
 import numpy as np
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element on 1st row:',arr[0,3])

4th element on 1st row: 4


In [27]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [29]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,1])

8


In [33]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,1])

5


In [35]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])

9


In [37]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1[1:2])



[2]


In [39]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [49]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
